- name: install docker in dev and prod servers
  hosts: prodserver:devserver
  become: yes
  gather_facts: no
  
  tasks:
  - name: Install required system packages
    apt:
     name: "{{ item }}"
     state: latest
     update_cache: yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools', 'python-pip', 'python-docker', 'python-apt']

  - name: Add Docker GPG apt Key
    apt_key:
     url: https://download.docker.com/linux/ubuntu/gpg
     state: present

  - name: Add Docker Repository
    apt_repository:
     repo: deb https://download.docker.com/linux/ubuntu bionic stable
     state: present

  - name: Update apt and install docker-ce
    apt:
     name: docker-ce
     state: latest
     update_cache: yes

  - name: Install Docker Module for Python for root user
    shell: pip install docker

  - name: login into docker hub
    docker_login:
      username: "{{ hub_user }}"
      password: "{{ hub_pass }}"
      reauthorize: yes
    register: login_results

  - debug:
      var: login_results
  
  - name: add ubuntu to docker group
    shell: sudo usermod -aG docker $USER
    become_user: ubuntu

  - name: install package
    apt:
     name: ['gnupg2', 'pass']
     state: present
     update_cache: yes
    become: yes
