- name: install jenkins using docker
  hosts: jenkinsci
  become: yes
  gather_facts: no

  vars:
   java_home: "/sites/jdk1.8.0_251"
   java_archive: "/sites/jdk-8u251-linux-x64.tar.gz"
   export_java: "export JAVA_HOME={{ java_home }}"
  
  tasks:
  - name: setting up key to access server directly from local
    authorized_key:
     user: ubuntu
     state: present
     key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

  - include: tasks/java.yml
  - include: tasks/jenkins.yml
  - include: tasks/docker.yml
